/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PesquisadoresIndexRouteImport } from './routes/pesquisadores.index'
import { Route as PesquisadoresIdRouteImport } from './routes/pesquisadores.$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisadoresIndexRoute = PesquisadoresIndexRouteImport.update({
  id: '/pesquisadores/',
  path: '/pesquisadores/',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisadoresIdRoute = PesquisadoresIdRouteImport.update({
  id: '/pesquisadores/$id',
  path: '/pesquisadores/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/assistente': typeof AssistenteRoute
  '/buscar': typeof BuscarRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/pesquisadores/$id': typeof PesquisadoresIdRoute
  '/pesquisadores/': typeof PesquisadoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/assistente': typeof AssistenteRoute
  '/buscar': typeof BuscarRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/pesquisadores/$id': typeof PesquisadoresIdRoute
  '/pesquisadores': typeof PesquisadoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/assistente': typeof AssistenteRoute
  '/buscar': typeof BuscarRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/pesquisadores/$id': typeof PesquisadoresIdRoute
  '/pesquisadores/': typeof PesquisadoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-docs'
    | '/assistente'
    | '/buscar'
    | '/configuracoes'
    | '/dashboard'
    | '/pesquisadores/$id'
    | '/pesquisadores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs'
    | '/assistente'
    | '/buscar'
    | '/configuracoes'
    | '/dashboard'
    | '/pesquisadores/$id'
    | '/pesquisadores'
  id:
    | '__root__'
    | '/'
    | '/api-docs'
    | '/assistente'
    | '/buscar'
    | '/configuracoes'
    | '/dashboard'
    | '/pesquisadores/$id'
    | '/pesquisadores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRoute: typeof ApiDocsRoute
  AssistenteRoute: typeof AssistenteRoute
  BuscarRoute: typeof BuscarRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  PesquisadoresIdRoute: typeof PesquisadoresIdRoute
  PesquisadoresIndexRoute: typeof PesquisadoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisadores/': {
      id: '/pesquisadores/'
      path: '/pesquisadores'
      fullPath: '/pesquisadores/'
      preLoaderRoute: typeof PesquisadoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisadores/$id': {
      id: '/pesquisadores/$id'
      path: '/pesquisadores/$id'
      fullPath: '/pesquisadores/$id'
      preLoaderRoute: typeof PesquisadoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRoute: ApiDocsRoute,
  AssistenteRoute: AssistenteRoute,
  BuscarRoute: BuscarRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  PesquisadoresIdRoute: PesquisadoresIdRoute,
  PesquisadoresIndexRoute: PesquisadoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
